# 此文件由makeobj.sh自动生成
############################################################
# 项目名 : 
# 模块名 : 
# 备  注 : 
############################################################

###### 源文件配置区

###### 目标文件、安装目录配置区
include ../makeinstall
NOCLEAN_OBJ	=	\
			vhm_ldd_and_cp_lib64.sh \
			vhm_profile_template.sh \
			vhm_etc_profile_template.sh \

NOCLEAN_OBJINST	=	$(_BINBASE)

###### 编译选项
CFLAGS		=	$(_CFLAGS) \

###### 链接选项
LFLAGS		=	$(_LFLAGS) \

###### 额外宏定义区
CLEAN_ADDITION	=

###### 加载mktpl模板库
#@ make_all
#@ make_clean
#@ make_install
#@ make_install_NOCLEAN_OBJINST
#@ make_uninstall
#@ make_uninstall_NOCLEAN_OBJINST
include $(MKTPL2_HOME)/makeobj_$(MKTPL2_OS).inc

###### 目标文件依赖关系

